# Generated by Django 3.0.6 on 2020-05-12 21:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('video_titles', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('video_thumbnails', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
                ('video_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
                ('total_sum_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hour', models.IntegerField()),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'api_statistic_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=256, unique=True)),
                ('author', models.CharField(max_length=512)),
                ('comment', models.CharField(blank=True, max_length=512, null=True)),
                ('date', models.CharField(max_length=512)),
                ('parsed_date', models.DateTimeField(db_index=True)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Szesnastka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=2048, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('video_url', models.URLField()),
                ('published_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
