# Generated by Django 3.0.6 on 2020-05-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=256, unique=True)),
                ('author', models.CharField(max_length=512)),
                ('comment', models.CharField(blank=True, max_length=512, null=True)),
                ('date', models.CharField(max_length=512)),
                ('parsed_date', models.DateTimeField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Szesnastka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=2048, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('video_url', models.URLField()),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
