# Generated by Django 3.0.6 on 2020-05-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='parsed_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='szesnastka',
            name='published_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
