# Generated by Django 3.0.6 on 2020-05-07 13:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200507_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('video_titles', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('video_thumbnails', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
                ('video_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
                ('total_sum_amount', models.FloatField()),
                ('hour', models.IntegerField()),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
            ],
            options={
                'db_table': 'api_statistic_view',
                'managed': False,
            },
        ),
    ]
